# Generated by Django 5.0.3 on 2024-04-17 04:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
